export const TARGET_COMPANY_CAREER_URL_OVERRIDES = Object.freeze({
  "servier": "https://jobs.servier.com/",
  "lvmh": "https://www.lvmh.com/fr/nous-rejoindre/nos-offres/",
  "geodis": "https://geodis.com/us-en/career",
  "sagemcom": "https://careers.sagemcom.com/offre-de-emploi/liste-toutes-offres.aspx",
  "contentsquare": "https://contentsquare.com/fr-fr/careers/",
  "artefact": "https://www.artefact.com/careers/explore-our-jobs/",
  "sia-partners": "https://www.sia-partners.com/fr/nous-rejoindre/carriere",
  "quantcube": "https://www.quant-cube.com/career-at-quantcube",
  "akur8": "https://www.akur8.com/career",
  "octo-technology": "https://octo.com/recrutement",
  "xxii": "https://xxii-group.welcomekit.co/",
  "alteia": "https://careers.alteia.com/",
  "veesion": "https://veesionvf.teamtailor.com/",
  "robovision-france": "https://robovision.ai/about-us/careers",
  "gleamer": "https://www.gleamer.ai/jobs",
  "azmed": "https://www.azmed.co/fr/career",
  "incepto": "https://incepto-medical.welcomekit.co/",
  "milvue": "https://www.milvue.com/join-us/",
  "diabeloop": "https://www.diabeloop.fr/carrieres-emplois",
  "cardiologs": "https://www.careers.philips.com/emea/en/france",
  "elsan-digital": "https://talents.groupe-elsan.com/fr/annonces",
  "kayrros": "https://www.kayrros.com/fr/career/",
  "kineis": "https://kineis.com/recrutement/",
  "anywaves": "https://anywaves.com/about-us/join-us/",
  "audionamix": "https://www.linkedin.com/company/audionamix/jobs/",
  "soitec": "https://careers-fr-soitec.icims.com/jobs/intro",
  "viveris": "https://www.viveris.fr/nous-rejoindre/",
  "astek": "https://astekjob.fr/",
  "scalian": "https://careers.scalian.com/jobs",
  "assystem": "https://www.assystem.com/fr/carriere/notre-processus-de-recrutement/",
  "mirakl": "https://www.mirakl.com/company/careers/",
  "manomano": "https://www.manomano.com/careers",
  "shadow": "https://www.welcometothejungle.com/fr/companies-v1/shadow/jobs",
  "scaleway": "https://www.scaleway.com/fr/carrieres/",
  "aircall": "https://aircall.io/careers/",
  "ringover": "https://careers.ringover.com/jobs",
  "lumapps": "https://job.lumapps.com/",
  "murex": "https://murex.wd3.myworkdayjobs.com/MurexCareerPage1",
  "shift4good": "https://blue-calliandra-922.notion.site/Shift4Good-Job-Board-153edfed62f6817087e3d9da7fb1a233",
  "deepki": "https://careers.deepki.com/jobs",
  "metron": "https://www.metron.energy/fr/carriere/",
  "sweep": "https://sweep.teamtailor.com/",
  "fieldbox": "https://www.fieldbox.ai/job-openings-fieldbox/",
  "cosmo-tech": "https://cosmotech.com/join-us/",
  "nam-r": "https://namr.com/nous-rejoindre/",
  "verkor": "https://verkor.com/rejoindre-lequipe/",
  "forvia": "https://www.forvia.com/en/careers",
  "easy-mile": "https://www.welcometothejungle.com/en/companies/easymile/jobs",
  "exwayz": "https://www.exwayz.com/jobs/",
  "wandercraft": "https://www.welcometothejungle.com/en/companies/wandercraft/jobs",
  "moon-surgical": "https://moonsurgical.notion.site/Moon-Surgical-Jobs-Board-7a646bb4294a417d96d93875bddb4998",
  "medadom": "https://www.welcometothejungle.com/fr/companies/medadom",
  "resilience-care": "https://jobs.ashbyhq.com/Resilience%20Care"
});

export function targetCompanyCareerUrlOverride(companyKey) {
  const key = String(companyKey ?? "").trim();
  return TARGET_COMPANY_CAREER_URL_OVERRIDES[key] || "";
}
