function targetCompanySeedRows_() {
  var rows = [
    ["airbus", "Airbus", "giant", 1, "Aerospace", "data-science,machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "verified", "airbus.com", "", "Airbus", "", "Civil/industrial roles only; offer-level defense filter remains mandatory."],
    ["safran", "Safran", "giant", 1, "Aerospace", "data-science,machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "verified", "safran-group.com", "", "Safran", "", "Civil/industrial roles only; offer-level defense filter remains mandatory."],
    ["alstom", "Alstom", "giant", 1, "Rail & Mobility", "data-science,machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "verified", "alstom.com", "", "Alstom", "", ""],
    ["renault-group", "Renault Group", "giant", 1, "Automotive", "data-science,machine-learning,computer-vision,signal-processing,image-processing,time-series,industrial-ai", "verified", "renaultgroup.com", "", "Renault Group", "", ""],
    ["stellantis", "Stellantis", "giant", 1, "Automotive", "data-science,machine-learning,computer-vision,signal-processing,image-processing,time-series,industrial-ai", "verified", "stellantis.com", "", "Stellantis", "", ""],
    ["valeo", "Valeo", "giant", 1, "Automotive Technology", "machine-learning,deep-learning,computer-vision,signal-processing,image-processing,industrial-ai", "verified", "valeo.com", "", "Valeo", "", ""],
    ["michelin", "Michelin", "giant", 1, "Industrial & Mobility", "data-science,machine-learning,computer-vision,time-series,industrial-ai", "verified", "michelin.com", "", "Michelin", "", ""],
    ["schneider-electric", "Schneider Electric", "giant", 1, "Energy Management", "data-science,machine-learning,computer-vision,signal-processing,time-series,industrial-ai", "verified", "se.com", "", "Schneider Electric", "", ""],
    ["siemens", "Siemens", "giant", 1, "Industrial Technology", "data-science,machine-learning,computer-vision,signal-processing,time-series,industrial-ai", "verified", "siemens.com", "", "Siemens", "", ""],
    ["bosch-france", "Bosch France", "giant", 1, "Industrial Technology", "data-science,machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "verified", "bosch.fr", "", "Bosch,Bosch France,Robert Bosch", "bosch-smartrecruiters", ""],
    ["saint-gobain", "Saint-Gobain", "giant", 2, "Materials", "data-science,machine-learning,computer-vision,image-processing,time-series,industrial-ai", "verified", "saint-gobain.com", "", "Saint-Gobain", "", ""],
    ["air-liquide", "Air Liquide", "giant", 1, "Industrial Gases & Health", "data-science,machine-learning,signal-processing,time-series,industrial-ai", "verified", "airliquide.com", "", "Air Liquide", "", ""],
    ["edf", "EDF", "giant", 1, "Energy", "data-science,machine-learning,signal-processing,time-series,industrial-ai", "verified", "edf.fr", "", "EDF", "", ""],
    ["engie", "ENGIE", "giant", 1, "Energy", "data-science,machine-learning,time-series,remote-sensing,industrial-ai", "verified", "engie.com", "", "ENGIE", "", ""],
    ["totalenergies", "TotalEnergies", "giant", 1, "Energy", "data-science,machine-learning,computer-vision,signal-processing,remote-sensing,time-series,industrial-ai", "verified", "totalenergies.com", "", "TotalEnergies", "", ""],
    ["sncf", "SNCF", "giant", 1, "Rail & Mobility", "data-science,machine-learning,computer-vision,signal-processing,image-processing,time-series,industrial-ai", "verified", "sncf.com", "", "SNCF", "", ""],
    ["orange", "Orange", "giant", 1, "Telecommunications", "data-science,machine-learning,deep-learning,signal-processing,audio-speech,time-series,industrial-ai", "verified", "orange.com", "", "Orange", "", ""],
    ["thales-civil", "Thales", "giant", 2, "Digital & Aerospace Systems", "data-science,machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "verified", "thalesgroup.com", "", "Thales", "", "Civil/digital roles only; defense-oriented offers remain excluded."],
    ["stmicroelectronics", "STMicroelectronics", "giant", 1, "Semiconductors", "machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "verified", "st.com", "", "STMicroelectronics", "", ""],
    ["capgemini", "Capgemini", "giant", 1, "Technology Services", "data-science,machine-learning,deep-learning,computer-vision,image-processing,industrial-ai", "verified", "capgemini.com", "", "Capgemini", "", ""],
    ["accenture", "Accenture", "giant", 2, "Technology Services", "data-science,machine-learning,deep-learning,multimodal-ai,industrial-ai", "verified", "accenture.com", "", "Accenture", "", ""],
    ["ibm-france", "IBM France", "giant", 1, "Technology", "data-science,machine-learning,deep-learning,multimodal-ai,time-series", "verified", "ibm.com", "", "IBM,IBM France", "", ""],
    ["microsoft-france", "Microsoft France", "giant", 1, "Cloud & Software", "data-science,machine-learning,deep-learning,computer-vision,multimodal-ai", "verified", "microsoft.com", "", "Microsoft,Microsoft France", "", ""],
    ["google-france", "Google France", "giant", 1, "Technology", "data-science,machine-learning,deep-learning,computer-vision,multimodal-ai", "verified", "google.com", "", "Google,Google France", "", ""],
    ["amazon-france", "Amazon France", "giant", 1, "Technology & E-commerce", "data-science,machine-learning,deep-learning,computer-vision,time-series,industrial-ai", "verified", "amazon.jobs", "", "Amazon,Amazon France,AWS", "", ""],
    ["sap-france", "SAP France", "giant", 2, "Enterprise Software", "data-science,machine-learning,time-series,industrial-ai", "verified", "sap.com", "", "SAP,SAP France", "", ""],
    ["oracle-france", "Oracle France", "giant", 2, "Cloud & Software", "data-science,machine-learning,industrial-ai", "verified", "oracle.com", "", "Oracle,Oracle France", "", ""],
    ["dassault-systemes", "Dassault Systèmes", "giant", 1, "Industrial Software", "data-science,machine-learning,computer-vision,image-processing,signal-processing,industrial-ai", "verified", "3ds.com", "", "Dassault Systèmes", "", ""],
    ["eviden", "Eviden", "giant", 2, "Digital & Advanced Computing", "data-science,machine-learning,deep-learning,computer-vision,industrial-ai", "verified", "eviden.com", "", "Eviden", "", ""],
    ["sopra-steria", "Sopra Steria", "giant", 2, "Technology Services", "data-science,machine-learning,industrial-ai", "verified", "soprasteria.com", "", "Sopra Steria", "", ""],
    ["atos", "Atos", "giant", 3, "Technology Services", "data-science,machine-learning,industrial-ai", "verified", "atos.net", "", "Atos", "", ""],
    ["publicis-groupe", "Publicis Groupe", "giant", 2, "Marketing Technology", "data-science,machine-learning,computer-vision,multimodal-ai", "verified", "publicisgroupe.com", "", "Publicis Groupe", "publicis-smartrecruiters", ""],
    ["visa", "Visa", "giant", 2, "Payments", "data-science,machine-learning,time-series", "verified", "visa.com", "", "Visa", "visa-smartrecruiters", ""],
    ["mastercard", "Mastercard", "giant", 2, "Payments", "data-science,machine-learning,time-series", "verified", "mastercard.com", "", "Mastercard", "", ""],
    ["bnp-paribas", "BNP Paribas", "giant", 1, "Banking", "data-science,machine-learning,time-series", "verified", "group.bnpparibas", "", "BNP Paribas", "", ""],
    ["societe-generale", "Société Générale", "giant", 1, "Banking", "data-science,machine-learning,time-series", "verified", "societegenerale.com", "", "Société Générale,Societe Generale,SG", "", ""],
    ["credit-agricole", "Crédit Agricole", "giant", 2, "Banking", "data-science,machine-learning,time-series", "verified", "credit-agricole.com", "", "Crédit Agricole,Credit Agricole", "", ""],
    ["bpce", "Groupe BPCE", "giant", 2, "Banking", "data-science,machine-learning,time-series", "verified", "groupebpce.com", "", "Groupe BPCE", "", ""],
    ["axa", "AXA", "giant", 1, "Insurance", "data-science,machine-learning,time-series", "verified", "axa.com", "", "AXA", "", ""],
    ["allianz-france", "Allianz France", "giant", 2, "Insurance", "data-science,machine-learning,time-series", "verified", "allianz.fr", "", "Allianz,Allianz France", "", ""],
    ["amundi", "Amundi", "giant", 2, "Asset Management", "data-science,machine-learning,time-series", "verified", "amundi.com", "", "Amundi", "", ""],
    ["euronext", "Euronext", "giant", 1, "Financial Markets", "data-science,machine-learning,time-series", "verified", "euronext.com", "", "Euronext", "", ""],
    ["sanofi", "Sanofi", "giant", 1, "Pharmaceuticals", "data-science,machine-learning,deep-learning,medical-imaging,multimodal-ai,time-series", "verified", "sanofi.com", "", "Sanofi", "", ""],
    ["servier", "Servier", "giant", 2, "Pharmaceuticals", "data-science,machine-learning,medical-imaging,time-series", "verified", "servier.com", "", "Servier", "", ""],
    ["ipsen", "Ipsen", "giant", 2, "Pharmaceuticals", "data-science,machine-learning,medical-imaging,time-series", "verified", "ipsen.com", "", "Ipsen", "", ""],
    ["loreal", "L'Oréal", "giant", 1, "Consumer & Beauty", "data-science,machine-learning,computer-vision,image-processing,time-series", "verified", "loreal.com", "", "L'Oréal,Loreal", "", ""],
    ["lvmh", "LVMH", "giant", 2, "Luxury", "data-science,machine-learning,computer-vision,image-processing,time-series", "verified", "lvmh.com", "", "LVMH", "", ""],
    ["christian-dior", "Parfums Christian Dior", "giant", 2, "Luxury & Beauty", "data-science,machine-learning,computer-vision,image-processing", "verified", "dior.com", "", "Christian Dior,Parfums Christian Dior,Dior", "", ""],
    ["danone", "Danone", "giant", 1, "Food & Consumer", "data-science,machine-learning,computer-vision,image-processing,time-series", "verified", "danone.com", "", "Danone", "", ""],
    ["essilorluxottica", "EssilorLuxottica", "giant", 1, "Optics & Health", "data-science,machine-learning,computer-vision,image-processing,medical-imaging,industrial-ai", "verified", "essilorluxottica.com", "", "EssilorLuxottica", "", ""],
    ["decathlon", "Decathlon Digital", "giant", 1, "Retail Technology", "data-science,machine-learning,computer-vision,image-processing,time-series", "verified", "decathlon.com", "", "Decathlon,Decathlon Digital", "decathlon-greenhouse", ""],
    ["carrefour", "Carrefour", "giant", 2, "Retail", "data-science,machine-learning,computer-vision,time-series", "verified", "carrefour.com", "", "Carrefour", "", ""],
    ["auchan", "Auchan Retail", "giant", 3, "Retail", "data-science,machine-learning,time-series", "verified", "auchan-retail.com", "", "Auchan Retail", "", ""],
    ["veolia", "Veolia", "giant", 2, "Environmental Services", "data-science,machine-learning,computer-vision,time-series,industrial-ai", "verified", "veolia.com", "", "Veolia", "", ""],
    ["suez", "SUEZ", "giant", 2, "Environmental Services", "data-science,machine-learning,computer-vision,time-series,industrial-ai", "verified", "suez.com", "", "SUEZ", "", ""],
    ["vinci", "VINCI", "giant", 2, "Construction & Infrastructure", "data-science,machine-learning,computer-vision,image-processing,industrial-ai", "verified", "vinci.com", "", "VINCI", "", ""],
    ["bouygues", "Bouygues", "giant", 2, "Construction & Telecom", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "verified", "bouygues.com", "", "Bouygues", "", ""],
    ["eiffage", "Eiffage", "giant", 3, "Construction & Infrastructure", "data-science,machine-learning,computer-vision,industrial-ai", "verified", "eiffage.com", "", "Eiffage", "", ""],
    ["geodis", "GEODIS", "giant", 3, "Logistics", "data-science,machine-learning,time-series,industrial-ai", "verified", "geodis.com", "", "GEODIS", "", ""],
    ["air-france-klm", "Air France-KLM", "giant", 2, "Aviation", "data-science,machine-learning,time-series,industrial-ai", "verified", "airfranceklm.com", "", "Air France-KLM", "", ""],
    ["ge-healthcare-france", "GE HealthCare France", "giant", 1, "Medical Technology", "data-science,machine-learning,deep-learning,medical-imaging,image-processing,signal-processing", "verified", "gehealthcare.com", "", "GE HealthCare,GE Healthcare France", "", ""],
    ["philips-france", "Philips France", "giant", 1, "Health Technology", "machine-learning,medical-imaging,image-processing,signal-processing", "verified", "philips.fr", "", "Philips,Philips France", "", ""],
    ["siemens-healthineers-france", "Siemens Healthineers France", "giant", 1, "Medical Technology", "machine-learning,deep-learning,medical-imaging,image-processing,signal-processing", "verified", "siemens-healthineers.com", "", "Siemens Healthineers,Siemens Healthineers France", "", ""],
    ["roche-france", "Roche France", "giant", 2, "Healthcare", "data-science,machine-learning,medical-imaging,multimodal-ai", "verified", "roche.fr", "", "Roche,Roche France", "", ""],
    ["novartis-france", "Novartis France", "giant", 2, "Pharmaceuticals", "data-science,machine-learning,medical-imaging,time-series", "verified", "novartis.com", "", "Novartis,Novartis France", "", ""],
    ["astrazeneca-france", "AstraZeneca France", "giant", 2, "Pharmaceuticals", "data-science,machine-learning,medical-imaging,time-series", "verified", "astrazeneca.fr", "", "AstraZeneca,AstraZeneca France", "", ""],
    ["merck-france", "Merck France", "giant", 2, "Life Sciences", "data-science,machine-learning,medical-imaging,time-series", "verified", "merckgroup.com", "", "Merck,Merck France", "", ""],
    ["sagemcom", "Sagemcom", "giant", 1, "Telecom & Electronics", "machine-learning,deep-learning,signal-processing,image-processing,industrial-ai", "verified", "sagemcom.com", "", "Sagemcom", "", ""],
    ["nokia-france", "Nokia France", "giant", 1, "Telecommunications", "data-science,machine-learning,signal-processing,audio-speech,time-series", "verified", "nokia.com", "", "Nokia,Nokia France", "", ""],
    ["ericsson-france", "Ericsson France", "giant", 2, "Telecommunications", "data-science,machine-learning,signal-processing,time-series", "verified", "ericsson.com", "", "Ericsson,Ericsson France", "", ""],
    ["mistral-ai", "Mistral AI", "recognized", 1, "Artificial Intelligence", "machine-learning,deep-learning,multimodal-ai", "verified", "mistral.ai", "", "Mistral,Mistral AI", "mistral-ashby", ""],
    ["datadog", "Datadog", "recognized", 1, "Cloud Observability", "data-science,machine-learning,time-series", "verified", "datadoghq.com", "", "Datadog", "datadog-greenhouse", ""],
    ["doctolib", "Doctolib", "recognized", 1, "Health Technology", "data-science,machine-learning,time-series", "verified", "doctolib.fr", "", "Doctolib", "doctolib-greenhouse", ""],
    ["back-market", "Back Market", "recognized", 2, "E-commerce Technology", "data-science,machine-learning,time-series", "verified", "backmarket.com", "", "Back Market", "backmarket-ashby", ""],
    ["alan", "Alan", "recognized", 2, "Insurtech", "data-science,machine-learning,time-series", "verified", "alan.com", "", "Alan", "alan-ashby", ""],
    ["nabla", "Nabla", "recognized", 1, "Health AI", "machine-learning,deep-learning,multimodal-ai,audio-speech", "verified", "nabla.com", "", "Nabla", "nabla-ashby", ""],
    ["owkin", "Owkin", "recognized", 1, "Biomedical AI", "data-science,machine-learning,deep-learning,medical-imaging,multimodal-ai", "verified", "owkin.com", "", "Owkin", "owkin-ashby", ""],
    ["pennylane", "Pennylane", "recognized", 2, "Fintech Software", "data-science,machine-learning,time-series", "verified", "pennylane.com", "", "Pennylane", "pennylane-ashby", ""],
    ["h-company", "H Company", "recognized", 1, "Artificial Intelligence", "machine-learning,deep-learning,multimodal-ai", "verified", "hcompany.ai", "", "H,H Company", "hcompany-ashby", ""],
    ["photoroom", "Photoroom", "recognized", 1, "Imaging AI", "machine-learning,deep-learning,computer-vision,image-processing,multimodal-ai", "verified", "photoroom.com", "", "Photoroom", "photoroom-ashby", ""],
    ["dust", "Dust", "recognized", 2, "Artificial Intelligence", "machine-learning,deep-learning,multimodal-ai", "verified", "dust.tt", "", "Dust", "dust-ashby", ""],
    ["gladia", "Gladia", "recognized", 1, "Speech AI", "machine-learning,deep-learning,audio-speech,multimodal-ai", "verified", "gladia.io", "", "Gladia", "gladia-ashby", ""],
    ["ubisoft", "Ubisoft", "recognized", 1, "Gaming Technology", "data-science,machine-learning,computer-vision,image-processing,audio-speech", "verified", "ubisoft.com", "", "Ubisoft", "ubisoft-smartrecruiters", ""],
    ["poolside", "Poolside", "recognized", 1, "Artificial Intelligence", "machine-learning,deep-learning,multimodal-ai", "verified", "poolside.ai", "", "Poolside", "poolside-ashby", ""],
    ["dataiku", "Dataiku", "recognized", 1, "Data & AI Software", "data-science,machine-learning,industrial-ai", "verified", "dataiku.com", "", "Dataiku", "dataiku-greenhouse", ""],
    ["blablacar", "BlaBlaCar", "recognized", 2, "Mobility Technology", "data-science,machine-learning,time-series", "verified", "blablacar.com", "", "BlaBlaCar", "blablacar-lever", ""],
    ["pivot", "Pivot", "recognized", 2, "Enterprise Software", "data-science,machine-learning", "verified", "pivotapp.ai", "", "Pivot", "pivot-ashby", ""],
    ["hugging-face", "Hugging Face", "recognized", 1, "Artificial Intelligence", "machine-learning,deep-learning,multimodal-ai,audio-speech,computer-vision", "verified", "huggingface.co", "", "Hugging Face", "huggingface-greenhouse", ""],
    ["qonto", "Qonto", "recognized", 2, "Fintech", "data-science,machine-learning,time-series", "verified", "qonto.com", "", "Qonto", "qonto-ashby", ""],
    ["pigment", "Pigment", "recognized", 2, "Enterprise Planning", "data-science,machine-learning,time-series", "verified", "pigment.com", "", "Pigment", "pigment-ashby", ""],
    ["contentsquare", "Contentsquare", "recognized", 2, "Digital Analytics", "data-science,machine-learning,time-series", "verified", "contentsquare.com", "", "Contentsquare", "contentsquare-greenhouse", ""],
    ["criteo", "Criteo", "recognized", 1, "Advertising Technology", "data-science,machine-learning,deep-learning,time-series", "verified", "criteo.com", "", "Criteo", "criteo-greenhouse", ""],
    ["shift-technology", "Shift Technology", "recognized", 1, "Insurance AI", "data-science,machine-learning,deep-learning", "verified", "shift-technology.com", "", "Shift Technology", "shifttechnology-lever", ""],
    ["ekimetrics", "Ekimetrics", "recognized", 1, "Data Science Consulting", "data-science,machine-learning,deep-learning,time-series", "verified", "ekimetrics.com", "", "Ekimetrics", "", ""],
    ["artefact", "Artefact", "recognized", 1, "Data & AI Consulting", "data-science,machine-learning,deep-learning", "verified", "artefact.com", "", "Artefact", "", ""],
    ["sia-partners", "Sia", "recognized", 2, "Data & AI Consulting", "data-science,machine-learning,time-series", "probable", "sia-partners.com", "", "Sia", "", ""],
    ["quantmetry", "Quantmetry", "recognized", 1, "Data Science Consulting", "data-science,machine-learning,deep-learning,time-series", "probable", "quantmetry.com", "", "Quantmetry", "", ""],
    ["la-javaness", "La Javaness", "recognized", 2, "AI Consulting", "data-science,machine-learning,deep-learning,multimodal-ai", "probable", "lajavaness.com", "", "La Javaness", "", ""],
    ["quantcube", "QuantCube Technology", "recognized", 1, "Alternative Data", "data-science,machine-learning,time-series,remote-sensing", "probable", "quant-cube.com", "", "QuantCube Technology", "", ""],
    ["akur8", "Akur8", "recognized", 1, "Insurance AI", "data-science,machine-learning,time-series", "probable", "akur8.com", "", "Akur8", "", ""],
    ["octo-technology", "OCTO Technology", "recognized", 2, "Technology Consulting", "data-science,machine-learning,industrial-ai", "probable", "octo.com", "", "OCTO Technology", "", ""],
    ["prophesee", "Prophesee", "recognized", 1, "Computer Vision", "machine-learning,deep-learning,computer-vision,image-processing,signal-processing", "verified", "prophesee.ai", "", "Prophesee", "", ""],
    ["xxii", "XXII", "recognized", 1, "Computer Vision", "machine-learning,deep-learning,computer-vision,image-processing", "probable", "xxii.fr", "", "XXII,XXII Group", "", ""],
    ["exotec", "Exotec", "recognized", 1, "Robotics & Logistics", "machine-learning,computer-vision,image-processing,industrial-ai", "verified", "exotec.com", "", "Exotec", "", ""],
    ["alteia", "Alteia", "recognized", 1, "Geospatial AI", "machine-learning,computer-vision,image-processing,remote-sensing,industrial-ai", "probable", "alteia.com", "", "Alteia", "", ""],
    ["veesion", "Veesion", "recognized", 1, "Computer Vision", "machine-learning,deep-learning,computer-vision,image-processing", "probable", "veesion.io", "", "Veesion", "", ""],
    ["robovision-france", "Robovision France", "recognized", 2, "Computer Vision", "machine-learning,deep-learning,computer-vision,image-processing,industrial-ai", "probable", "robovision.ai", "", "Robovision France", "", ""],
    ["gleamer", "Gleamer", "recognized", 1, "Medical Imaging AI", "machine-learning,deep-learning,medical-imaging,image-processing", "verified", "gleamer.ai", "", "Gleamer", "", ""],
    ["sonio", "Sonio", "recognized", 1, "Medical Imaging AI", "machine-learning,deep-learning,medical-imaging,image-processing,multimodal-ai", "probable", "sonio.ai", "", "Sonio", "", ""],
    ["azmed", "AZmed", "recognized", 1, "Medical Imaging AI", "machine-learning,deep-learning,medical-imaging,image-processing", "probable", "azmed.co", "", "AZmed", "", ""],
    ["incepto", "Incepto", "recognized", 1, "Medical Imaging AI", "machine-learning,deep-learning,medical-imaging,image-processing", "probable", "incepto-medical.com", "", "Incepto", "", ""],
    ["milvue", "Milvue", "recognized", 1, "Medical Imaging AI", "machine-learning,deep-learning,medical-imaging,image-processing", "probable", "milvue.com", "", "Milvue", "", ""],
    ["volta-medical", "Volta Medical", "recognized", 1, "Medical AI", "machine-learning,deep-learning,medical-imaging,signal-processing", "probable", "volta-medical.com", "", "Volta Medical", "", ""],
    ["withings", "Withings", "recognized", 1, "Digital Health", "data-science,machine-learning,signal-processing,time-series,medical-imaging", "verified", "withings.com", "", "Withings", "", ""],
    ["diabeloop", "Diabeloop", "recognized", 1, "Digital Health", "data-science,machine-learning,signal-processing,time-series", "probable", "diabeloop.com", "", "Diabeloop", "", ""],
    ["cardiologs", "Cardiologs", "recognized", 1, "Medical Signal AI", "machine-learning,deep-learning,signal-processing,time-series", "probable", "cardiologs.com", "", "Cardiologs", "", ""],
    ["implicity", "Implicity", "recognized", 1, "Cardiac Digital Health", "data-science,machine-learning,signal-processing,time-series", "probable", "implicity.com", "", "Implicity", "", ""],
    ["elsan-digital", "ELSAN Digital", "recognized", 2, "Healthcare", "data-science,machine-learning,medical-imaging,time-series", "probable", "elsan.care", "", "ELSAN Digital", "", ""],
    ["kayrros", "Kayrros", "recognized", 1, "Climate & Geospatial AI", "data-science,machine-learning,computer-vision,remote-sensing,time-series", "verified", "kayrros.com", "", "Kayrros", "", ""],
    ["cls-group", "CLS", "recognized", 1, "Space & Geospatial", "data-science,machine-learning,remote-sensing,time-series,signal-processing", "probable", "cls.fr", "", "CLS,Collecte Localisation Satellites", "", ""],
    ["kineis", "Kinéis", "recognized", 2, "Satellite IoT", "data-science,machine-learning,signal-processing,remote-sensing,time-series", "probable", "kineis.com", "", "Kinéis,Kineis", "", ""],
    ["exotrail", "Exotrail", "recognized", 2, "Space Technology", "data-science,machine-learning,signal-processing,time-series,industrial-ai", "probable", "exotrail.com", "", "Exotrail", "", ""],
    ["anywaves", "ANYWAVES", "recognized", 2, "Space Technology", "signal-processing,industrial-ai", "probable", "anywaves.com", "", "ANYWAVES", "", ""],
    ["kermap", "Kermap", "recognized", 2, "Geospatial AI", "data-science,machine-learning,computer-vision,remote-sensing,image-processing", "probable", "kermap.com", "", "Kermap", "", ""],
    ["devialet", "Devialet", "recognized", 1, "Audio Technology", "machine-learning,signal-processing,audio-speech", "verified", "devialet.com", "", "Devialet", "", ""],
    ["sonos-france", "Sonos France", "recognized", 2, "Audio Technology", "machine-learning,signal-processing,audio-speech", "probable", "sonos.com", "", "Sonos France", "", ""],
    ["ircam-amplify", "IRCAM Amplify", "recognized", 2, "Audio Technology", "machine-learning,signal-processing,audio-speech", "probable", "ircamamplify.com", "", "IRCAM Amplify", "", ""],
    ["audionamix", "Audionamix", "recognized", 2, "Audio AI", "machine-learning,deep-learning,signal-processing,audio-speech", "probable", "audionamix.com", "", "Audionamix", "", ""],
    ["sonarworks-france", "Sonarworks France", "recognized", 3, "Audio Technology", "machine-learning,signal-processing,audio-speech", "probable", "sonarworks.com", "", "Sonarworks France", "", ""],
    ["ekinops", "Ekinops", "recognized", 1, "Telecommunications", "machine-learning,signal-processing,time-series,industrial-ai", "verified", "ekinops.com", "", "Ekinops", "", ""],
    ["sequans", "Sequans Communications", "recognized", 1, "Semiconductors & Telecom", "machine-learning,signal-processing,industrial-ai", "verified", "sequans.com", "", "Sequans Communications", "", ""],
    ["kalray", "Kalray", "recognized", 1, "Semiconductors & Edge AI", "machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "kalrayinc.com", "", "Kalray", "", ""],
    ["soitec", "Soitec", "recognized", 2, "Semiconductors", "data-science,machine-learning,industrial-ai", "verified", "soitec.com", "", "Soitec", "", ""],
    ["tronic-s-microsystems", "Tronics Microsystems", "recognized", 2, "Sensors & Semiconductors", "signal-processing,industrial-ai", "probable", "tronicsgroup.com", "", "Tronics Microsystems", "", ""],
    ["viveris", "Viveris", "recognized", 2, "Engineering Services", "machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "probable", "viveris.fr", "", "Viveris", "", ""],
    ["akkodis", "Akkodis", "recognized", 2, "Engineering Services", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "akkodis.com", "", "Akkodis", "", ""],
    ["alten", "ALTEN", "recognized", 2, "Engineering Services", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "alten.com", "", "ALTEN", "", ""],
    ["expleo", "Expleo", "recognized", 2, "Engineering Services", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "expleo.com", "", "Expleo", "", ""],
    ["sii", "SII", "recognized", 2, "Engineering Services", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "sii-group.com", "", "SII", "", ""],
    ["astek", "Astek", "recognized", 2, "Engineering Services", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "astekgroup.fr", "", "Astek", "", ""],
    ["agap2", "agap2", "recognized", 3, "Engineering Services", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "agap2.com", "", "agap2", "", ""],
    ["scalian", "Scalian", "recognized", 2, "Engineering Services", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "scalian.com", "", "Scalian", "", ""],
    ["assystem", "Assystem", "recognized", 2, "Engineering Services", "data-science,machine-learning,signal-processing,time-series,industrial-ai", "probable", "assystem.com", "", "Assystem", "", ""],
    ["setec", "setec", "recognized", 3, "Engineering & Infrastructure", "data-science,machine-learning,computer-vision,time-series,industrial-ai", "probable", "setec.fr", "", "setec", "", ""],
    ["egis", "Egis", "recognized", 3, "Engineering & Infrastructure", "data-science,machine-learning,computer-vision,remote-sensing,time-series,industrial-ai", "probable", "egis-group.com", "", "Egis", "", ""],
    ["artelia", "Artelia", "recognized", 3, "Engineering & Infrastructure", "data-science,machine-learning,remote-sensing,time-series,industrial-ai", "probable", "arteliagroup.com", "", "Artelia", "", ""],
    ["akeneo", "Akeneo", "recognized", 2, "Enterprise Software", "data-science,machine-learning,multimodal-ai", "probable", "akeneo.com", "", "Akeneo", "", ""],
    ["mirakl", "Mirakl", "recognized", 2, "Enterprise Software", "data-science,machine-learning,time-series", "probable", "mirakl.com", "", "Mirakl", "", ""],
    ["manomano", "ManoMano", "recognized", 2, "E-commerce Technology", "data-science,machine-learning,computer-vision,time-series", "probable", "manomano.com", "", "ManoMano", "", ""],
    ["vestiaire-collective", "Vestiaire Collective", "recognized", 2, "E-commerce Technology", "data-science,machine-learning,computer-vision,image-processing", "probable", "vestiairecollective.com", "", "Vestiaire Collective", "", ""],
    ["deezer", "Deezer", "recognized", 1, "Audio & Streaming", "data-science,machine-learning,deep-learning,audio-speech,time-series", "verified", "deezer.com", "", "Deezer", "", ""],
    ["dailymotion", "Dailymotion", "recognized", 2, "Video Technology", "data-science,machine-learning,computer-vision,image-processing,multimodal-ai", "probable", "dailymotion.com", "", "Dailymotion", "", ""],
    ["shadow", "Shadow", "recognized", 3, "Cloud Technology", "data-science,machine-learning,time-series", "probable", "shadow.tech", "", "Shadow", "", ""],
    ["ovhcloud", "OVHcloud", "recognized", 1, "Cloud Infrastructure", "data-science,machine-learning,time-series,industrial-ai", "verified", "ovhcloud.com", "", "OVHcloud", "", ""],
    ["scaleway", "Scaleway", "recognized", 1, "Cloud Infrastructure", "data-science,machine-learning,industrial-ai", "verified", "scaleway.com", "", "Scaleway", "", ""],
    ["clever-cloud", "Clever Cloud", "recognized", 3, "Cloud Infrastructure", "data-science,machine-learning,time-series", "probable", "clever-cloud.com", "", "Clever Cloud", "", ""],
    ["outscale", "OUTSCALE", "recognized", 2, "Cloud Infrastructure", "data-science,machine-learning,industrial-ai", "probable", "outscale.com", "", "OUTSCALE", "", ""],
    ["platform-sh", "Platform.sh", "recognized", 2, "Cloud Infrastructure", "data-science,machine-learning,time-series", "probable", "platform.sh", "", "Platform.sh", "", ""],
    ["talend", "Talend", "recognized", 2, "Data Software", "data-science,machine-learning", "probable", "talend.com", "", "Talend", "", ""],
    ["aircall", "Aircall", "recognized", 2, "Communications Software", "data-science,machine-learning,audio-speech,time-series", "probable", "aircall.io", "", "Aircall", "", ""],
    ["ringover", "Ringover", "recognized", 2, "Communications Software", "data-science,machine-learning,audio-speech,time-series", "probable", "ringover.com", "", "Ringover", "", ""],
    ["botify", "Botify", "recognized", 2, "Search Technology", "data-science,machine-learning,time-series", "probable", "botify.com", "", "Botify", "", ""],
    ["algolia", "Algolia", "recognized", 1, "Search & AI", "data-science,machine-learning,deep-learning,multimodal-ai", "probable", "algolia.com", "", "Algolia", "", ""],
    ["lumapps", "LumApps", "recognized", 3, "Enterprise Software", "data-science,machine-learning,multimodal-ai", "probable", "lumapps.com", "", "LumApps", "", ""],
    ["murex", "Murex", "recognized", 1, "Financial Software", "data-science,machine-learning,time-series", "verified", "murex.com", "", "Murex", "", ""],
    ["symphonyai-france", "SymphonyAI France", "recognized", 2, "Enterprise AI", "data-science,machine-learning,industrial-ai", "probable", "symphonyai.com", "", "SymphonyAI France", "", ""],
    ["shift4good", "Shift4Good", "recognized", 3, "Climate & Mobility", "data-science,machine-learning,time-series", "probable", "shift4good.com", "", "Shift4Good", "", ""],
    ["deepki", "Deepki", "recognized", 1, "Climate Technology", "data-science,machine-learning,time-series", "probable", "deepki.com", "", "Deepki", "", ""],
    ["metron", "METRON", "recognized", 1, "Energy AI", "data-science,machine-learning,time-series,industrial-ai", "probable", "metron.energy", "", "METRON", "", ""],
    ["greenly", "Greenly", "recognized", 2, "Climate Technology", "data-science,machine-learning,time-series", "probable", "greenly.earth", "", "Greenly", "", ""],
    ["sweep", "Sweep", "recognized", 2, "Climate Technology", "data-science,machine-learning,time-series", "probable", "sweep.net", "", "Sweep", "", ""],
    ["fieldbox", "Fieldbox", "recognized", 1, "Industrial AI", "data-science,machine-learning,time-series,industrial-ai", "probable", "fieldbox.ai", "", "Fieldbox", "", ""],
    ["cosmo-tech", "Cosmo Tech", "recognized", 1, "Simulation & AI", "data-science,machine-learning,time-series,industrial-ai", "probable", "cosmotech.com", "", "Cosmo Tech", "", ""],
    ["nam-r", "namR", "recognized", 2, "Geospatial Data", "data-science,machine-learning,remote-sensing,image-processing", "probable", "namr.com", "", "namR", "", ""],
    ["descartes-underwriting", "Descartes Underwriting", "recognized", 1, "Climate Risk", "data-science,machine-learning,remote-sensing,time-series", "probable", "descartesunderwriting.com", "", "Descartes Underwriting", "", ""],
    ["iceye-france", "ICEYE France", "recognized", 2, "Earth Observation", "machine-learning,computer-vision,remote-sensing,image-processing,time-series", "probable", "iceye.com", "", "ICEYE France", "", ""],
    ["planet-france", "Planet France", "recognized", 2, "Earth Observation", "machine-learning,computer-vision,remote-sensing,image-processing,time-series", "probable", "planet.com", "", "Planet France", "", ""],
    ["edf-renouvelables", "EDF Renouvelables", "recognized", 2, "Renewable Energy", "data-science,machine-learning,remote-sensing,time-series,industrial-ai", "probable", "edf-renouvelables.com", "", "EDF Renouvelables", "", ""],
    ["neoen", "Neoen", "recognized", 2, "Renewable Energy", "data-science,machine-learning,time-series,industrial-ai", "probable", "neoen.com", "", "Neoen", "", ""],
    ["verkor", "Verkor", "recognized", 1, "Battery Technology", "data-science,machine-learning,computer-vision,time-series,industrial-ai", "probable", "verkor.com", "", "Verkor", "", ""],
    ["forvia", "FORVIA", "recognized", 1, "Automotive Technology", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "forvia.com", "", "FORVIA,Faurecia", "", ""],
    ["plastic-omnium", "OPmobility", "recognized", 2, "Automotive Technology", "data-science,machine-learning,computer-vision,signal-processing,industrial-ai", "probable", "opmobility.com", "", "OPmobility,Plastic Omnium", "", ""],
    ["navya-mobility", "Navya Mobility", "recognized", 2, "Autonomous Mobility", "machine-learning,deep-learning,computer-vision,signal-processing,image-processing", "probable", "navya.tech", "", "Navya Mobility", "", ""],
    ["easy-mile", "EasyMile", "recognized", 1, "Autonomous Mobility", "machine-learning,deep-learning,computer-vision,signal-processing,image-processing", "probable", "easymile.com", "", "EasyMile,Easy Mile", "", ""],
    ["outsight", "Outsight", "recognized", 1, "LiDAR & Spatial AI", "machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "probable", "outsight.ai", "", "Outsight", "", ""],
    ["exwayz", "Exwayz", "recognized", 1, "LiDAR & Robotics", "machine-learning,computer-vision,signal-processing,image-processing,industrial-ai", "probable", "exwayz.fr", "", "Exwayz", "", ""],
    ["ganymed-robotics", "Ganymed Robotics", "recognized", 1, "Medical Robotics", "machine-learning,computer-vision,medical-imaging,image-processing", "probable", "ganymedrobotics.com", "", "Ganymed Robotics", "", ""],
    ["wandercraft", "Wandercraft", "recognized", 1, "Medical Robotics", "data-science,machine-learning,signal-processing,time-series,industrial-ai", "probable", "wandercraft.eu", "", "Wandercraft", "", ""],
    ["moon-surgical", "Moon Surgical", "recognized", 1, "Medical Robotics", "machine-learning,computer-vision,medical-imaging,image-processing", "probable", "moonsurgical.com", "", "Moon Surgical", "", ""],
    ["medtech-zimmer-biomet", "Zimmer Biomet Robotics France", "recognized", 2, "Medical Robotics", "machine-learning,computer-vision,medical-imaging,image-processing", "probable", "zimmerbiomet.com", "", "Zimmer Biomet Robotics France", "", ""],
    ["bio-serenity", "BioSerenity", "recognized", 1, "Digital Health", "data-science,machine-learning,signal-processing,time-series", "probable", "bioserenity.com", "", "BioSerenity", "", ""],
    ["medadom", "MEDADOM", "recognized", 2, "Digital Health", "data-science,machine-learning,time-series", "probable", "medadom.com", "", "MEDADOM", "", ""],
    ["doctolib-siilo", "Siilo by Doctolib", "recognized", 3, "Health Software", "data-science,machine-learning,multimodal-ai", "probable", "siilo.com", "", "Siilo by Doctolib", "", ""],
    ["cureety", "Cureety", "recognized", 2, "Digital Health", "data-science,machine-learning,time-series", "probable", "cureety.com", "", "Cureety", "", ""],
    ["resilience-care", "Resilience", "recognized", 1, "Digital Health", "data-science,machine-learning,time-series,multimodal-ai", "probable", "resilience.care", "", "Resilience", "", ""],
    ["aqemia", "Aqemia", "recognized", 1, "Drug Discovery AI", "data-science,machine-learning,deep-learning,multimodal-ai", "probable", "aqemia.com", "", "Aqemia", "", ""],
    ["ibiology-france", "Iktos", "recognized", 1, "Drug Discovery AI", "data-science,machine-learning,deep-learning,multimodal-ai", "probable", "iktos.ai", "", "Iktos", "", ""],
    ["dna-script", "DNA Script", "recognized", 2, "Biotechnology", "data-science,machine-learning,signal-processing,industrial-ai", "probable", "dnascript.com", "", "DNA Script", "", ""],
    ["pasqal", "PASQAL", "recognized", 1, "Quantum Computing", "data-science,machine-learning,signal-processing,industrial-ai", "verified", "pasqal.com", "", "PASQAL", "", ""],
    ["alice-bob", "Alice & Bob", "recognized", 2, "Quantum Computing", "data-science,machine-learning,signal-processing", "probable", "alice-bob.com", "", "Alice & Bob", "", ""]
  ];

  return rows.map(function(row) {
    return {
      companyKey: row[0],
      companyName: row[1],
      companyClass: row[2],
      priorityTier: row[3],
      sector: row[4],
      specializations: row[5],
      francePresence: row[6],
      officialDomain: row[7],
      careersUrl: row[8],
      aliases: row[9],
      sourceKeys: row[10],
      notes: row[11]
    };
  });
}
